---
# 1. Deploiement de l'application Node.js
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-lacets
spec:
  replicas: 1 # Nombre de pods par défaut
  selector:
    matchLabels:
      app: api-lacets
  template:
    metadata:
      labels:
        app: api-lacets
    spec:
      containers:
        - name: api
          image: loicdesry/api-lacets:latest # image récupérée depuis le Docker Hub (à modifier pour autre PC)
          ports:
            - containerPort: 3000
          env:
            # L'API utilise le nom du Service MySQL pour s'y connecter
            - name: DB_HOST
              value: "mysql-service"
            - name: MYSQL_HOST
              value: "mysql-service"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "rootpassword"
            - name: MYSQL_DB
              value: "my_db"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "rootpassword"
            - name: DB_NAME
              value: "my_db"
            - name: PORT
              value: "3000"
          # Définit ce que le conteneur a le droit de consommer sur la VM.
          resources:
            requests:
              cpu: "100m"   # Demande minimum garantie
              memory: "128Mi"
            limits:
              cpu: "200m"   # Plafond maximum autorisé
              memory: "256Mi"
---
# 2. Service (NodePort)
# Il ouvre un port sur la machine virtuelle pour qu'on puisse y accéder depuis notre navigateur.
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api-lacets
  ports:
    - protocol: TCP
      port: 80 # Le port d'écoute interne du service
      targetPort: 3000 # Le vrai port du conteneur Node.js
---
# 3. Régulateur

# Surveille la consommation CPU de l'API. Si elle dépasse 50% de sa limite,
# Kubernetes créera des clones de l'API (jusqu'à 3 max) pour aider.
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-lacets
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
