---
# ==============================================================================
# ÉTAPE 1 : INSTALLATION DE NODE EXPORTER SUR TOUTES LES MACHINES (K3S + MONITOR)
# ==============================================================================
- name: Configuration des agents (Node Exporter)
  hosts: all
  become: yes # On exécute en tant que root (sudo)
  tasks:
    - name: Mettre à jour le cache APT
      apt:
        update_cache: yes

    - name: Installer prometheus-node-exporter
      apt:
        name: prometheus-node-exporter
        state: present

    - name: S'assurer que Node Exporter est démarré et activé au boot
      systemd:
        name: prometheus-node-exporter
        state: started
        enabled: yes

# ==============================================================================
# ÉTAPE 2 : INSTALLATION DU CERVEAU (PROMETHEUS) ET DE L'AFFICHAGE (GRAFANA)
# ==============================================================================
- name: Configuration du serveur de Monitoring
  hosts: monitoring
  become: yes
  vars:
    # On va chercher l'IP de la machine K3s dans l'inventaire pour l'injecter dans Prometheus
    ip_k3s: "{{ hostvars[groups['k3s_master'][0]]['ansible_host'] }}"

  tasks:
    # --- PROMETHEUS ---
    - name: Installer Prometheus
      apt:
        name: prometheus
        state: present

    - name: Envoyer le fichier de configuration Prometheus
      template:
        src: ./prometheus.yml
        dest: /etc/prometheus/prometheus.yml
      notify: Restart Prometheus # Si le fichier change, redémarrer Prometheus

    # --- GRAFANA ---
    - name: Installer les dépendances pour Grafana
      apt:
        name:
          - apt-transport-https
          - software-properties-common
          - wget
          - gnupg
        state: present

    - name: Ajouter la clé de sécurité Grafana
      apt_key:
        url: https://apt.grafana.com/gpg.key
        state: present

    - name: Ajouter le dépôt officiel Grafana
      apt_repository:
        repo: deb https://apt.grafana.com stable main
        state: present

    - name: Installer Grafana
      apt:
        name: grafana
        state: present
        update_cache: yes
        dpkg_options: 'force-confdef,force-confold'
      environment:
        DEBIAN_FRONTEND: noninteractive
        NEEDRESTART_MODE: a
        NEEDRESTART_SUSPEND: 1

    - name: S'assurer que Grafana est démarré et activé au boot
      systemd:
        name: grafana-server
        state: started
        enabled: yes

  # --- GESTIONNAIRES (HANDLERS) ---
  handlers:
    - name: Restart Prometheus
      systemd:
        name: prometheus
        state: restarted
