name: Deploiement Automatique (CI/CD)

on:
  push:
    branches:
      - main

jobs:
  deploiement:
    runs-on: self-hosted

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Déploiement VM Principale (Partie 1)
        working-directory: ./Partie1
        run: |
          [ -f terraform.tfstate ] && mv terraform.tfstate terraform.tfstate.cache || echo "No state"
          rm -rf .terraform .terraform.lock.hcl
          terraform init
          [ -f terraform.tfstate.cache ] && mv terraform.tfstate.cache terraform.tfstate || echo "No cache to restore"
          terraform apply -auto-approve

      - name: Déploiement VM Monitoring (Partie 5)
        working-directory: ./Partie5
        run: |
          [ -f terraform.tfstate ] && mv terraform.tfstate terraform.tfstate.cache || echo "No state"
          rm -rf .terraform .terraform.lock.hcl
          terraform init
          [ -f terraform.tfstate.cache ] && mv terraform.tfstate.cache terraform.tfstate || echo "No cache to restore"
          terraform apply -auto-approve

      - name: Récupération des IPs et création inventaire
        working-directory: ./Partie1
        run: |
          chmod +x get_ip.sh
          ./get_ip.sh
          # On exporte les IPs pour que GitHub Actions s'en souvienne pour la suite
          echo "VM_IP=$(terraform output -raw vm_ip)" >> $GITHUB_ENV
          cd ../Partie5
          echo "MONITOR_IP=$(terraform output -raw monitor_ip)" >> $GITHUB_ENV

      - name: Connexion et Push Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-lacets:latest ./Partie2/api-lacets
          docker push ${{ secrets.DOCKER_USERNAME }}/api-lacets:latest


      - name: Installation K3s (Mode Rapide Air-Gap)
        run: |
          echo "=== Téléchargement du binaire sur le Runner ==="
          curl -Lo k3s https://github.com/k3s-io/k3s/releases/download/v1.30.0+k3s1/k3s
          echo "=== Attente du démarrage complet du SSH ==="
          sleep 20
          echo "=== Test de connexion rapide ==="
          ping -c 3 ${{ env.VM_IP }}
          echo "=== Envoi du binaire vers la VM ==="
          sshpass -p "vagrant" scp -v -o StrictHostKeyChecking=no -o ConnectTimeout=10 k3s vagrant@${{ env.VM_IP }}:/tmp/k3s
          echo "=== Installation locale ==="
          sshpass -p "vagrant" ssh -o StrictHostKeyChecking=no vagrant@${{ env.VM_IP }} "sudo mv /tmp/k3s /usr/local/bin/k3s && sudo chmod +x /usr/local/bin/k3s && curl -sfL https://get.k3s.io | INSTALL_K3S_SKIP_DOWNLOAD=true sh -"

      - name: Déploiement sur Kubernetes
        working-directory: ./Partie3
        run: |
          sshpass -p "vagrant" scp -o StrictHostKeyChecking=no mysql.yaml api.yaml vagrant@${{ env.VM_IP }}:~
          sshpass -p "vagrant" ssh -o StrictHostKeyChecking=no vagrant@${{ env.VM_IP }} "sudo /usr/local/bin/k3s kubectl apply -f mysql.yaml && sudo /usr/local/bin/k3s kubectl apply -f api.yaml"

      - name: Déploiement du Monitoring (Ansible)
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook -i inventory.ini Partie5/setup_monitoring.yml -vvv
